env: "local" # local, dev, prod
storage_config:
  host: "school-db"
  port: "5432"
  username: "postgres"
  password: "qwerty"
  db_name: "postgres"
  ssl_mode: "disable"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
